LITE-21209: Added backoff retry reconnection
cloudblue/connect-extension-runner pull request #35
Opened 2021-11-23 09:31 UTC by gab832

2021-11-23 15:17 UTC, ffaraoneim requested changes

2021-11-23 15:17 UTC, ffaraoneim commented on connect/eaas/config.py
> +    def get_version(self):
This function should be moved outside config.

2021-11-23 15:17 UTC, ffaraoneim commented on connect/eaas/config.py
> +            f'connect-extension-runner/{version} {self.env["environment_id"]}/'
Personally I would prefer that environment and instance to be at the end of the user agent string.

2021-11-23 15:17 UTC, ffaraoneim commented on connect/eaas/config.py
> +            ('User-Agent', self.get_user_agent()),
Customized User-Agent is for ConnectClient instances (both sync and async) not for the websocket.

2021-11-23 15:17 UTC, ffaraoneim commented on connect/eaas/worker.py
> +    ordinal_attempt = ordinal.get(details["tries"], 'th')
Could you please replace double quotes for single ones ?

2021-11-24 11:56 UTC, ffaraoneim approved these changes

2021-11-24 11:57 UTC, marcserrat approved these changes

2021-11-24 11:57 UTC, merged