LITE-25177: deleted get_routers logic, now this logic is in connect-e…
cloudblue/connect-extension-runner pull request #98
Opened 2022-09-21 16:20 UTC by gab832

…aas-core

2022-09-21 17:18 UTC, ffaraone requested changes

2022-09-21 17:18 UTC, ffaraone commented on tests/handlers/test_web.py
> +        def get_routers(cls):
It's a bit strange that you overrides this method and than patch it below.
Why not to declare at the beginning of the test function:

auth_router = mocker.MagicMock()
no_auth_router = mocker.MagicMock()

then make this method return this two mock objects ?

2022-09-22 07:35 UTC, ffaraone approved these changes

2022-09-22 07:46 UTC, marcserrat approved these changes

2022-09-22 07:46 UTC, merged